%% exportdata.m
% Exports digitized and force data from the '_ALL.mat' files that save all
% the data generated by the MatLab code Ian created.


%%
% gather all files ending in '*_ALL.mat'
files = dir('*_ALL.mat');

% loop through each file and output specific data
for cnt = 1:length(files)
    % load data
    load(files(cnt).name, 'WristXYZ', 'ElbowXYZ', 'ShoulderXYZ', 'F_o')
    
    % digitized data
    dig_wrist = WristXYZ;
    dig_elbow = ElbowXYZ;
    dig_shoulder = ShoulderXYZ;
    
    % center of mass data
    %cm_forearm = p_fArm;
    %cm_upperarm = p_uArm;
    
    % segmental acceleration data
    %acc_forearm = a_fArm;
    %acc_upperarm = a_uArm;
    
    % force data
    force = F_o;
    
    % create table
    tab_out = array2table([dig_wrist, dig_elbow, dig_shoulder, force],...
        'VariableNames', {'wrist_x', 'wrist_y', 'wrist_z',...
        'elbow_x', 'elbow_y', 'elbow_z',...
        'shoulder_x', 'shoulder_y', 'shoulder_z',...
        'fx', 'fy', 'fz'});
    
    % create new file name
    filename = [files(cnt).name(1:length(files(cnt).name)-8), '.xlsx'];
    writetable(tab_out, filename)
    
    % clear vars
    clearvars -except files cnt
end